name: errcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_go112:
    name: 'go 1.12.x'
    runs-on: ubuntu-latest
    env:
      GO111MODULE: 'on'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12.17
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  build_go113:
    name: 'go 1.13.x'
    runs-on: ubuntu-latest
    env:
      GO111MODULE: 'on'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.15
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  build_go114:
    name: 'go 1.14.x'
    runs-on: ubuntu-latest
    env:
      GO111MODULE: 'on'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.12
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  build_go115:
    name: 'go 1.15.x'
    runs-on: ubuntu-latest
    env:
      GO111MODULE: 'on'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.6
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  build_go118:
    name: 'go 1.18.x'
    runs-on: ubuntu-latest
    env:
      GO111MODULE: 'on'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
